name: bandwidth-throttling
description: Action to throttle the bandwidth on MacOS runner

runs:
  using: composite
  steps:
    - name: throttle bandwidth down
      shell: bash
      run: |

        # echo "dummynet in from mobile-e2e-site-1.test.mattermost.cloud to any pipe 1
        # dummynet out from any to mobile-e2e-site-1.test.mattermost.cloud pipe 2" | sudo pfctl -f -

        echo "dummynet in from mobile-e2e-site-1.test.mattermost.cloud to ! 127.0.0.1 pipe 1
        dummynet out from ! 127.0.0.1 to mobile-e2e-site-1.test.mattermost.cloud pipe 2" | sudo pfctl -f -
        
        # pipe 1 is download, below is 3.3Mb/s with average of 500ms latency
        sudo dnctl pipe 1 config bw 3300Kbit/s delay 500ms
        
        # pipe 2 is upload, below is 3.3Mb/s with 500ms latency
        sudo dnctl pipe 2 config bw 3300Kbit/s delay 500ms

        sleep 2;
        
        sudo pfctl -E

        sleep 5;

    - name: test curl after throttling
      shell: bash
      run: |
        curl -o /dev/null -m 20 -s -w 'Total: %{time_total}s\n' 'https://community.mattermost.com/api/v4/system/ping?get_server_status=true&abc=134'

        curl -o /dev/null -m 20 -s -w 'Total: %{time_total}s\n' 'https://mobile-e2e-site-1.test.mattermost.cloud/api/v4/system/ping?get_server_status=true&abc=134'
